

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_input_U0"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_input_U0.flow_control_loop_pipe_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_buffer_fu_4198"},
	{"ID" : "8", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_buffer_fu_4198.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_left_right_fu_5228"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_left_right_fu_5228.sparsemux_2049_10_8_1_1_U1031"},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_left_right_fu_5228.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_left_right_fu_5228.frp_pipeline_valid_U"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_left_right_fu_5228.pf_left_stream_U"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_left_right_fu_5228.pf_right_stream_U"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_merge_fu_6262"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_merge_fu_6262.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_buffer_write_fu_6269"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_buffer_write_fu_6269.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_output_fu_7301"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_output_fu_7301.sparsemux_2049_10_8_1_1_U3093"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.grp_merge_sort_iterative_Pipeline_output_fu_7301.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.left_stream_fifo_U"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.right_stream_fifo_U"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.merge_sort_iterative_U0.temp_stream_fifo_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_output_U0"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_output_U0.flow_control_loop_pipe_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.output_r_c_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.input_stream_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.output_stream_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_write_output_U0_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_merge_sort_iterative_U0_U"}]}
set DependenceCheckSize 0
