-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity merge_sort_merge_sort_iterative_Pipeline_merge is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    left_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    left_stream_empty_n : IN STD_LOGIC;
    left_stream_read : OUT STD_LOGIC;
    right_stream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    right_stream_empty_n : IN STD_LOGIC;
    right_stream_read : OUT STD_LOGIC;
    temp_stream_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    temp_stream_full_n : IN STD_LOGIC;
    temp_stream_write : OUT STD_LOGIC );
end;


architecture behav of merge_sort_merge_sort_iterative_Pipeline_merge is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_phi_mux_left_empty_phi_fu_80_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_nbreadreq_fu_42_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op19_read_state1 : BOOLEAN;
    signal ap_phi_mux_right_empty_phi_fu_91_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_nbreadreq_fu_56_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op26_read_state1 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal or_ln19_reg_217 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln19_reg_217_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln20_reg_231 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op45_write_state3 : BOOLEAN;
    signal ap_predicate_op46_write_state3 : BOOLEAN;
    signal left_empty_1_reg_99 : STD_LOGIC_VECTOR (0 downto 0);
    signal left_empty_1_reg_99_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal right_empty_1_reg_114 : STD_LOGIC_VECTOR (0 downto 0);
    signal right_empty_1_reg_114_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op48_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_left_empty_1_phi_fu_102_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_right_empty_1_phi_fu_117_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal temp_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal left_stream_blk_n : STD_LOGIC;
    signal right_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal or_ln19_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal left_val_2_reg_221 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_val_2_reg_226 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln20_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal ap_phi_mux_left_empty_2_phi_fu_134_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_right_empty_2_phi_fu_154_p8 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_left_empty_1_reg_99 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_right_empty_1_reg_114 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_left_empty_2_reg_129 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_left_empty_2_reg_129 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_right_empty_2_reg_149 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_right_empty_2_reg_149 : STD_LOGIC_VECTOR (0 downto 0);
    signal left_val_fu_34 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal right_val_fu_38 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_300 : BOOLEAN;
    signal ap_condition_192 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component merge_sort_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component merge_sort_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_left_empty_2_reg_129_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_left_empty_1_phi_fu_102_p6 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_right_empty_1_phi_fu_117_p6 = ap_const_lv1_0) and (ap_phi_mux_left_empty_1_phi_fu_102_p6 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                ap_phi_reg_pp0_iter1_left_empty_2_reg_129 <= ap_const_lv1_1;
            elsif (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ap_phi_reg_pp0_iter1_left_empty_2_reg_129 <= ap_phi_reg_pp0_iter0_left_empty_2_reg_129;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_right_empty_2_reg_149_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_192)) then
                if ((ap_phi_mux_left_empty_1_phi_fu_102_p6 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter1_right_empty_2_reg_149 <= ap_phi_mux_right_empty_1_phi_fu_117_p6;
                elsif (((ap_phi_mux_right_empty_1_phi_fu_117_p6 = ap_const_lv1_0) and (ap_phi_mux_left_empty_1_phi_fu_102_p6 = ap_const_lv1_1))) then 
                    ap_phi_reg_pp0_iter1_right_empty_2_reg_149 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_right_empty_2_reg_149 <= ap_phi_reg_pp0_iter0_right_empty_2_reg_149;
                end if;
            end if; 
        end if;
    end process;

    left_empty_1_reg_99_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_9_nbreadreq_fu_42_p3 = ap_const_lv1_0) and (ap_phi_mux_left_empty_phi_fu_80_p4 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                left_empty_1_reg_99 <= ap_const_lv1_1;
            elsif ((((tmp_9_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (ap_phi_mux_left_empty_phi_fu_80_p4 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_phi_mux_left_empty_phi_fu_80_p4 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                left_empty_1_reg_99 <= ap_const_lv1_0;
            elsif ((not(((ap_phi_mux_right_empty_1_phi_fu_117_p6 = ap_const_lv1_1) and (ap_phi_mux_left_empty_1_phi_fu_102_p6 = ap_const_lv1_1))) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                left_empty_1_reg_99 <= ap_phi_reg_pp0_iter0_left_empty_1_reg_99;
            end if; 
        end if;
    end process;

    right_empty_1_reg_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_0) and (ap_phi_mux_right_empty_phi_fu_91_p4 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                right_empty_1_reg_114 <= ap_const_lv1_1;
            elsif ((((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_phi_mux_right_empty_phi_fu_91_p4 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_phi_mux_right_empty_phi_fu_91_p4 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                right_empty_1_reg_114 <= ap_const_lv1_0;
            elsif ((not(((ap_phi_mux_right_empty_1_phi_fu_117_p6 = ap_const_lv1_1) and (ap_phi_mux_left_empty_1_phi_fu_102_p6 = ap_const_lv1_1))) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                right_empty_1_reg_114 <= ap_phi_reg_pp0_iter0_right_empty_1_reg_114;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln20_reg_231 <= icmp_ln20_fu_191_p2;
                left_empty_1_reg_99_pp0_iter1_reg <= left_empty_1_reg_99;
                left_val_2_reg_221 <= left_val_fu_34;
                or_ln19_reg_217 <= or_ln19_fu_179_p2;
                or_ln19_reg_217_pp0_iter1_reg <= or_ln19_reg_217;
                right_empty_1_reg_114_pp0_iter1_reg <= right_empty_1_reg_114;
                right_val_2_reg_226 <= right_val_fu_38;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_9_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (ap_phi_mux_left_empty_phi_fu_80_p4 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                left_val_fu_34 <= left_stream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_phi_mux_right_empty_phi_fu_91_p4 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                right_val_fu_38 <= right_stream_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state1_pp0_stage0_iter0, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(left_stream_empty_n, ap_predicate_op19_read_state1, right_stream_empty_n, ap_predicate_op26_read_state1)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (((ap_predicate_op26_read_state1 = ap_const_boolean_1) and (right_stream_empty_n = ap_const_logic_0)) or ((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (left_stream_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(temp_stream_full_n, ap_predicate_op45_write_state3, ap_predicate_op46_write_state3, left_empty_1_reg_99_pp0_iter1_reg, ap_predicate_op48_write_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (((ap_predicate_op48_write_state3 = ap_const_boolean_1) and (temp_stream_full_n = ap_const_logic_0)) or ((left_empty_1_reg_99_pp0_iter1_reg = ap_const_lv1_0) and (temp_stream_full_n = ap_const_logic_0)) or ((ap_predicate_op46_write_state3 = ap_const_boolean_1) and (temp_stream_full_n = ap_const_logic_0)) or ((ap_predicate_op45_write_state3 = ap_const_boolean_1) and (temp_stream_full_n = ap_const_logic_0)));
    end process;


    ap_condition_192_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_192 <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_300_assign_proc : process(ap_enable_reg_pp0_iter1, or_ln19_reg_217, left_empty_1_reg_99, right_empty_1_reg_114, ap_block_pp0_stage0)
    begin
                ap_condition_300 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and ((or_ln19_reg_217 = ap_const_lv1_0) or ((right_empty_1_reg_114 = ap_const_lv1_0) or (left_empty_1_reg_99 = ap_const_lv1_0))));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_phi_mux_left_empty_1_phi_fu_102_p6, ap_phi_mux_right_empty_1_phi_fu_117_p6, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_right_empty_1_phi_fu_117_p6 = ap_const_lv1_1) and (ap_phi_mux_left_empty_1_phi_fu_102_p6 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, left_empty_1_reg_99, right_empty_1_reg_114, ap_block_pp0_stage0_subdone)
    begin
        if (((right_empty_1_reg_114 = ap_const_lv1_1) and (left_empty_1_reg_99 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_left_empty_1_phi_fu_102_p6_assign_proc : process(ap_phi_mux_left_empty_phi_fu_80_p4, tmp_9_nbreadreq_fu_42_p3, ap_phi_reg_pp0_iter0_left_empty_1_reg_99)
    begin
        if (((tmp_9_nbreadreq_fu_42_p3 = ap_const_lv1_0) and (ap_phi_mux_left_empty_phi_fu_80_p4 = ap_const_lv1_1))) then 
            ap_phi_mux_left_empty_1_phi_fu_102_p6 <= ap_const_lv1_1;
        elsif (((ap_phi_mux_left_empty_phi_fu_80_p4 = ap_const_lv1_0) or ((tmp_9_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (ap_phi_mux_left_empty_phi_fu_80_p4 = ap_const_lv1_1)))) then 
            ap_phi_mux_left_empty_1_phi_fu_102_p6 <= ap_const_lv1_0;
        else 
            ap_phi_mux_left_empty_1_phi_fu_102_p6 <= ap_phi_reg_pp0_iter0_left_empty_1_reg_99;
        end if; 
    end process;


    ap_phi_mux_left_empty_2_phi_fu_134_p8_assign_proc : process(or_ln19_reg_217, icmp_ln20_fu_191_p2, ap_phi_reg_pp0_iter1_left_empty_2_reg_129)
    begin
        if ((or_ln19_reg_217 = ap_const_lv1_0)) then
            if ((icmp_ln20_fu_191_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_left_empty_2_phi_fu_134_p8 <= ap_const_lv1_0;
            elsif ((icmp_ln20_fu_191_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_left_empty_2_phi_fu_134_p8 <= ap_const_lv1_1;
            else 
                ap_phi_mux_left_empty_2_phi_fu_134_p8 <= ap_phi_reg_pp0_iter1_left_empty_2_reg_129;
            end if;
        else 
            ap_phi_mux_left_empty_2_phi_fu_134_p8 <= ap_phi_reg_pp0_iter1_left_empty_2_reg_129;
        end if; 
    end process;


    ap_phi_mux_left_empty_phi_fu_80_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_phi_mux_left_empty_2_phi_fu_134_p8, ap_condition_300)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_300)) then 
                ap_phi_mux_left_empty_phi_fu_80_p4 <= ap_phi_mux_left_empty_2_phi_fu_134_p8;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_left_empty_phi_fu_80_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_left_empty_phi_fu_80_p4 <= ap_phi_mux_left_empty_2_phi_fu_134_p8;
            end if;
        else 
            ap_phi_mux_left_empty_phi_fu_80_p4 <= ap_phi_mux_left_empty_2_phi_fu_134_p8;
        end if; 
    end process;


    ap_phi_mux_right_empty_1_phi_fu_117_p6_assign_proc : process(ap_phi_mux_right_empty_phi_fu_91_p4, tmp_s_nbreadreq_fu_56_p3, ap_phi_reg_pp0_iter0_right_empty_1_reg_114)
    begin
        if (((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_0) and (ap_phi_mux_right_empty_phi_fu_91_p4 = ap_const_lv1_1))) then 
            ap_phi_mux_right_empty_1_phi_fu_117_p6 <= ap_const_lv1_1;
        elsif (((ap_phi_mux_right_empty_phi_fu_91_p4 = ap_const_lv1_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_phi_mux_right_empty_phi_fu_91_p4 = ap_const_lv1_1)))) then 
            ap_phi_mux_right_empty_1_phi_fu_117_p6 <= ap_const_lv1_0;
        else 
            ap_phi_mux_right_empty_1_phi_fu_117_p6 <= ap_phi_reg_pp0_iter0_right_empty_1_reg_114;
        end if; 
    end process;


    ap_phi_mux_right_empty_2_phi_fu_154_p8_assign_proc : process(or_ln19_reg_217, icmp_ln20_fu_191_p2, ap_phi_reg_pp0_iter1_right_empty_2_reg_149)
    begin
        if ((or_ln19_reg_217 = ap_const_lv1_0)) then
            if ((icmp_ln20_fu_191_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_right_empty_2_phi_fu_154_p8 <= ap_const_lv1_1;
            elsif ((icmp_ln20_fu_191_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_right_empty_2_phi_fu_154_p8 <= ap_const_lv1_0;
            else 
                ap_phi_mux_right_empty_2_phi_fu_154_p8 <= ap_phi_reg_pp0_iter1_right_empty_2_reg_149;
            end if;
        else 
            ap_phi_mux_right_empty_2_phi_fu_154_p8 <= ap_phi_reg_pp0_iter1_right_empty_2_reg_149;
        end if; 
    end process;


    ap_phi_mux_right_empty_phi_fu_91_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_phi_mux_right_empty_2_phi_fu_154_p8, ap_condition_300)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_300)) then 
                ap_phi_mux_right_empty_phi_fu_91_p4 <= ap_phi_mux_right_empty_2_phi_fu_154_p8;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_right_empty_phi_fu_91_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_right_empty_phi_fu_91_p4 <= ap_phi_mux_right_empty_2_phi_fu_154_p8;
            end if;
        else 
            ap_phi_mux_right_empty_phi_fu_91_p4 <= ap_phi_mux_right_empty_2_phi_fu_154_p8;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_left_empty_1_reg_99 <= "X";
    ap_phi_reg_pp0_iter0_left_empty_2_reg_129 <= "X";
    ap_phi_reg_pp0_iter0_right_empty_1_reg_114 <= "X";
    ap_phi_reg_pp0_iter0_right_empty_2_reg_149 <= "X";

    ap_predicate_op19_read_state1_assign_proc : process(ap_phi_mux_left_empty_phi_fu_80_p4, tmp_9_nbreadreq_fu_42_p3)
    begin
                ap_predicate_op19_read_state1 <= ((tmp_9_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (ap_phi_mux_left_empty_phi_fu_80_p4 = ap_const_lv1_1));
    end process;


    ap_predicate_op26_read_state1_assign_proc : process(ap_phi_mux_right_empty_phi_fu_91_p4, tmp_s_nbreadreq_fu_56_p3)
    begin
                ap_predicate_op26_read_state1 <= ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_phi_mux_right_empty_phi_fu_91_p4 = ap_const_lv1_1));
    end process;


    ap_predicate_op45_write_state3_assign_proc : process(or_ln19_reg_217_pp0_iter1_reg, icmp_ln20_reg_231)
    begin
                ap_predicate_op45_write_state3 <= ((icmp_ln20_reg_231 = ap_const_lv1_0) and (or_ln19_reg_217_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op46_write_state3_assign_proc : process(or_ln19_reg_217_pp0_iter1_reg, icmp_ln20_reg_231)
    begin
                ap_predicate_op46_write_state3 <= ((icmp_ln20_reg_231 = ap_const_lv1_1) and (or_ln19_reg_217_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op48_write_state3_assign_proc : process(left_empty_1_reg_99_pp0_iter1_reg, right_empty_1_reg_114_pp0_iter1_reg)
    begin
                ap_predicate_op48_write_state3 <= ((right_empty_1_reg_114_pp0_iter1_reg = ap_const_lv1_0) and (left_empty_1_reg_99_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln20_fu_191_p2 <= "1" when (unsigned(left_val_fu_34) > unsigned(right_val_fu_38)) else "0";

    left_stream_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, left_stream_empty_n, ap_predicate_op19_read_state1, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            left_stream_blk_n <= left_stream_empty_n;
        else 
            left_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    left_stream_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op19_read_state1, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_predicate_op19_read_state1 = ap_const_boolean_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            left_stream_read <= ap_const_logic_1;
        else 
            left_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    or_ln19_fu_179_p2 <= (ap_phi_mux_right_empty_1_phi_fu_117_p6 or ap_phi_mux_left_empty_1_phi_fu_102_p6);

    right_stream_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, right_stream_empty_n, ap_predicate_op26_read_state1, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_predicate_op26_read_state1 = ap_const_boolean_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            right_stream_blk_n <= right_stream_empty_n;
        else 
            right_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    right_stream_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_predicate_op26_read_state1, ap_block_pp0_stage0_11001, ap_start_int)
    begin
        if (((ap_predicate_op26_read_state1 = ap_const_boolean_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            right_stream_read <= ap_const_logic_1;
        else 
            right_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    temp_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, temp_stream_full_n, ap_predicate_op45_write_state3, ap_predicate_op46_write_state3, left_empty_1_reg_99_pp0_iter1_reg, ap_predicate_op48_write_state3, ap_block_pp0_stage0)
    begin
        if ((((ap_predicate_op48_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((left_empty_1_reg_99_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_predicate_op46_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_predicate_op45_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            temp_stream_blk_n <= temp_stream_full_n;
        else 
            temp_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    temp_stream_din_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op45_write_state3, ap_predicate_op46_write_state3, left_empty_1_reg_99_pp0_iter1_reg, ap_predicate_op48_write_state3, left_val_2_reg_221, right_val_2_reg_226, ap_block_pp0_stage0_01001)
    begin
        if ((((ap_predicate_op48_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001)) or ((ap_predicate_op46_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001)))) then 
            temp_stream_din <= right_val_2_reg_226;
        elsif ((((left_empty_1_reg_99_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001)) or ((ap_predicate_op45_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_01001)))) then 
            temp_stream_din <= left_val_2_reg_221;
        else 
            temp_stream_din <= "XXXXXXXX";
        end if; 
    end process;


    temp_stream_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op45_write_state3, ap_predicate_op46_write_state3, left_empty_1_reg_99_pp0_iter1_reg, ap_predicate_op48_write_state3, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op48_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((left_empty_1_reg_99_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op46_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op45_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            temp_stream_write <= ap_const_logic_1;
        else 
            temp_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_9_nbreadreq_fu_42_p3 <= (0=>(left_stream_empty_n), others=>'-');
    tmp_s_nbreadreq_fu_56_p3 <= (0=>(right_stream_empty_n), others=>'-');
end behav;
