// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module merge_sort_write_tmp (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        tmp_right_dout,
        tmp_right_num_data_valid,
        tmp_right_fifo_cap,
        tmp_right_empty_n,
        tmp_right_read,
        tmp_left_dout,
        tmp_left_num_data_valid,
        tmp_left_fifo_cap,
        tmp_left_empty_n,
        tmp_left_read,
        tmp_din,
        tmp_num_data_valid,
        tmp_fifo_cap,
        tmp_full_n,
        tmp_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] tmp_right_dout;
input  [2:0] tmp_right_num_data_valid;
input  [2:0] tmp_right_fifo_cap;
input   tmp_right_empty_n;
output   tmp_right_read;
input  [7:0] tmp_left_dout;
input  [2:0] tmp_left_num_data_valid;
input  [2:0] tmp_left_fifo_cap;
input   tmp_left_empty_n;
output   tmp_left_read;
output  [7:0] tmp_din;
input  [2:0] tmp_num_data_valid;
input  [2:0] tmp_fifo_cap;
input   tmp_full_n;
output   tmp_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg tmp_right_read;
reg tmp_left_read;
reg[7:0] tmp_din;
reg tmp_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_done;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_idle;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_ready;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_left_read;
wire   [7:0] grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_din;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_write;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_done;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_idle;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_ready;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_right_read;
wire   [7:0] grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_din;
wire    grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_write;
reg    grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start_reg;
reg    ap_block_state1_ignore_call4;
wire    ap_CS_fsm_state2;
reg    grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start_reg = 1'b0;
#0 grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start_reg = 1'b0;
end

merge_sort_write_tmp_Pipeline_VITIS_LOOP_108_1 grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start),
    .ap_done(grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_done),
    .ap_idle(grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_idle),
    .ap_ready(grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_ready),
    .tmp_left_dout(tmp_left_dout),
    .tmp_left_num_data_valid(3'd0),
    .tmp_left_fifo_cap(3'd0),
    .tmp_left_empty_n(tmp_left_empty_n),
    .tmp_left_read(grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_left_read),
    .tmp_din(grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_din),
    .tmp_num_data_valid(3'd0),
    .tmp_fifo_cap(3'd0),
    .tmp_full_n(tmp_full_n),
    .tmp_write(grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_write)
);

merge_sort_write_tmp_Pipeline_VITIS_LOOP_113_2 grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start),
    .ap_done(grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_done),
    .ap_idle(grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_idle),
    .ap_ready(grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_ready),
    .tmp_right_dout(tmp_right_dout),
    .tmp_right_num_data_valid(3'd0),
    .tmp_right_fifo_cap(3'd0),
    .tmp_right_empty_n(tmp_right_empty_n),
    .tmp_right_read(grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_right_read),
    .tmp_din(grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_din),
    .tmp_num_data_valid(3'd0),
    .tmp_fifo_cap(3'd0),
    .tmp_full_n(tmp_full_n),
    .tmp_write(grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state1_ignore_call4) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start_reg <= 1'b1;
        end else if ((grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_ready == 1'b1)) begin
            grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start_reg <= 1'b1;
        end else if ((grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_ready == 1'b1)) begin
            grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_din = grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_din;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_din = grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_din;
    end else begin
        tmp_din = grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_left_read = grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_left_read;
    end else begin
        tmp_left_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_right_read = grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_right_read;
    end else begin
        tmp_right_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_write = grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_tmp_write;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_write = grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_tmp_write;
    end else begin
        tmp_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call4 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start = grp_write_tmp_Pipeline_VITIS_LOOP_108_1_fu_22_ap_start_reg;

assign grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start = grp_write_tmp_Pipeline_VITIS_LOOP_113_2_fu_30_ap_start_reg;

assign start_out = real_start;

endmodule //merge_sort_write_tmp
